### ISSUE TITLE
Consider creating a minimal summary file *inside* the image

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/osbuilder#35]
Just a random idea...

It might be useful for `rootfs.sh` to create a plan text file *inside* the rootfs directory. That file could potentially be used for debugging and would include some basic details about the image such as:

- Base distro name image created from (`fedora`, `clearlinux`, etc).
- Base distro version image created from (`27`, `12345`, etc).
- Timestamp of when the rootfs was created
  Something like `date '+%Y-%m-%d.%H:%M:%S.%N%z'`
- Version of osbuilder used to create the image
- Build type (`default` or `custom` maybe where the latter would denote that extra packages had been added to the basic image [maybe for debugging]).with lots of extra packages?)
- *et cetera*

As for the format of this file, if we decide to do this, I vote for YAML :)

/cc @sboeuf as the agent could potentially use this?

**Comment by jcvenegas** [comment]
@jodh-intel what about a toml file or a json:
[rootfs]
distro_name=
version=
packages= ["systemd", "iptables", agent]
agent_version=<commit/sha/tag>
build_type= "default"

**Comment by jcvenegas** [comment]
@jodh-intel what could be the template for a YAML?

**Comment by jodh-intel** [comment]
@jcvenegas - it doesn't have to be YAML - I just personally prefer YAML over TOML as it's more flexible (and it looks better to my eyes ;).

If it was YAML, something like the following maybe:

```
osbuilder:
    url: https://github.com/kata-containers/osbuilder
    version: 052b8af49749066e9092c0f4a415ef86f037e929
    file-format-version: 1
description: My test image!
build-type: default
base-distro:
    name: CentOS
    version: 7
rootfs:
    creation-time: 2018-01-23.09:56:12.025966451+0000
    packages:
        - systemd
        - kata-agent
        - iptables
agent:
    name: kata-agent
    version: 0.0.1-e0287f098243545f05c74dafc81724d60a76cf59
```
